// AUTO-GENERATED by tools/generate_sprites.py - do not edit by hand.
import type { ImageSourcePropType } from 'react-native';
import type { SpriteData } from './types';
import raw from './spriteData.json';

export const SPRITES = raw as unknown as SpriteData;

export const PAGES: ImageSourcePropType[] = [
  require('./atlas/page0.png'),
  require('./atlas/page1.png'),
  require('./atlas/page2.png'),
  require('./atlas/page3.png'),
  require('./atlas/page4.png'),
];
