// AUTO-GENERATED by tools/generate_sprites.py - do not edit by hand.
import type { ImageSourcePropType } from 'react-native';
import type { SpriteData } from './types';
import raw from './spriteData.json';

export const SPRITES = raw as unknown as SpriteData;

export const PAGES: ImageSourcePropType[] = [
  require('./atlas/page0.png'),
  require('./atlas/page1.png'),
  require('./atlas/page2.png'),
  require('./atlas/page3.png'),
  require('./atlas/page4.png'),
  require('./atlas/page5.png'),
  require('./atlas/page6.png'),
  require('./atlas/page7.png'),
  require('./atlas/page8.png'),
  require('./atlas/page9.png'),
  require('./atlas/page10.png'),
  require('./atlas/page11.png'),
  require('./atlas/page12.png'),
  require('./atlas/page13.png'),
  require('./atlas/page14.png'),
  require('./atlas/page15.png'),
  require('./atlas/page16.png'),
  require('./atlas/page17.png'),
  require('./atlas/page18.png'),
  require('./atlas/page19.png'),
  require('./atlas/page20.png'),
  require('./atlas/page21.png'),
  require('./atlas/page22.png'),
  require('./atlas/page23.png'),
  require('./atlas/page24.png'),
  require('./atlas/page25.png'),
  require('./atlas/page26.png'),
  require('./atlas/page27.png'),
  require('./atlas/page28.png'),
  require('./atlas/page29.png'),
  require('./atlas/page30.png'),
  require('./atlas/page31.png'),
];
