// AUTO-GENERATED by tools/generate_logos.py - do not edit by hand.
import type { ImageSourcePropType } from 'react-native';
import teams from './teams.json';

export type LeagueTeam = (typeof teams)[number];
export const LEAGUE_TEAMS: LeagueTeam[] = teams;

/** Full round badge (512 x 512). */
export const TEAM_LOGOS: Record<string, ImageSourcePropType> = {
  "PHX": require('./png/PHX.png'),
  "SLC": require('./png/SLC.png'),
  "CHI": require('./png/CHI.png'),
  "CHA": require('./png/CHA.png'),
  "NY": require('./png/NY.png'),
  "GA": require('./png/GA.png'),
  "BOS": require('./png/BOS.png'),
  "ORL": require('./png/ORL.png'),
  "MIA": require('./png/MIA.png'),
  "NO": require('./png/NO.png'),
  "PHI": require('./png/PHI.png'),
  "BKN": require('./png/BKN.png'),
  "HOU": require('./png/HOU.png'),
  "DET": require('./png/DET.png'),
  "IND": require('./png/IND.png'),
  "SF": require('./png/SF.png'),
  "LAC": require('./png/LAC.png'),
  "LAB": require('./png/LAB.png'),
  "DC": require('./png/DC.png'),
  "DEN": require('./png/DEN.png'),
  "DAL": require('./png/DAL.png'),
  "SAC": require('./png/SAC.png'),
  "MIL": require('./png/MIL.png'),
  "POR": require('./png/POR.png'),
  "OKC": require('./png/OKC.png'),
  "SA": require('./png/SA.png'),
  "MIN": require('./png/MIN.png'),
  "CLE": require('./png/CLE.png'),
  "MEM": require('./png/MEM.png'),
  "TOR": require('./png/TOR.png'),
};

/** Icon only, transparent (384 x 384). */
export const TEAM_ICONS: Record<string, ImageSourcePropType> = {
  "PHX": require('./png/PHX_icon.png'),
  "SLC": require('./png/SLC_icon.png'),
  "CHI": require('./png/CHI_icon.png'),
  "CHA": require('./png/CHA_icon.png'),
  "NY": require('./png/NY_icon.png'),
  "GA": require('./png/GA_icon.png'),
  "BOS": require('./png/BOS_icon.png'),
  "ORL": require('./png/ORL_icon.png'),
  "MIA": require('./png/MIA_icon.png'),
  "NO": require('./png/NO_icon.png'),
  "PHI": require('./png/PHI_icon.png'),
  "BKN": require('./png/BKN_icon.png'),
  "HOU": require('./png/HOU_icon.png'),
  "DET": require('./png/DET_icon.png'),
  "IND": require('./png/IND_icon.png'),
  "SF": require('./png/SF_icon.png'),
  "LAC": require('./png/LAC_icon.png'),
  "LAB": require('./png/LAB_icon.png'),
  "DC": require('./png/DC_icon.png'),
  "DEN": require('./png/DEN_icon.png'),
  "DAL": require('./png/DAL_icon.png'),
  "SAC": require('./png/SAC_icon.png'),
  "MIL": require('./png/MIL_icon.png'),
  "POR": require('./png/POR_icon.png'),
  "OKC": require('./png/OKC_icon.png'),
  "SA": require('./png/SA_icon.png'),
  "MIN": require('./png/MIN_icon.png'),
  "CLE": require('./png/CLE_icon.png'),
  "MEM": require('./png/MEM_icon.png'),
  "TOR": require('./png/TOR_icon.png'),
};
