// AUTO-GENERATED by tools/generate_trails.py - do not edit by hand.
import type { ImageSourcePropType } from 'react-native';
import type { TrailId } from './trails';

/** One strip per trail, required lazily so only trails in use are loaded. */
export const TRAIL_IMAGES: Record<TrailId, () => ImageSourcePropType> = {
  none: () => require('./none.png'),
  fire: () => require('./fire.png'),
  laser: () => require('./laser.png'),
  bubbles: () => require('./bubbles.png'),
  money: () => require('./money.png'),
  lightning: () => require('./lightning.png'),
  rainbow: () => require('./rainbow.png'),
  ice: () => require('./ice.png'),
  smoke: () => require('./smoke.png'),
  stars: () => require('./stars.png'),
  confetti: () => require('./confetti.png'),
  afterimage: () => require('./afterimage.png'),
};

export const BALL_IMAGE: ImageSourcePropType = require('./ball.png');
